# https://realpython.com/dockerizing-flask-with-compose-and-machine-from-localhost-to-the-cloud/

# https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-with-docker-compose-es

version: "3"
services:
  wordpress:
    container_name: chule_wordpress
    image: wordpress
    ports:
      - "8080:80"
    links:
      - mysql
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "12345"
      WORDPRESS_DB_NAME: wordpress
  mysql:
    container_name: chule_mysql
    image: mysql:5.7
    volumes:
      - ./.mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "12345"

volumes:
  wp-content:
  .mysql:
